
server:
    port: 8085

spring:
    application:
        name: FRONT-END

eureka:
    client:
        service-url:
            defaultUrl: ${EUREKA.URI:http://localhost:8761/eureka/}
        instance:
            preferIpAddress: true