
server:
    port: 8081

spring:
    application:
        name: FRONT-END

    datasource:
        username: postgres
        password: 1402
        url: jdbc:postgresql://localhost:5433/city_front
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: smtp.gmail.com
        port: 587
        username: rentmanagement.teenagers@gmail.com
        password: esbhggiatjdqhhzx
        properties:
            mjaail:
                smtp:
                    auth: true
            mail:
                smtp:
                    starttls:
                        enable: true

services:
    user-service: http://localhost:8080
